GET http://localhost:8080/api HTTP/1.1
Accept: application/json

###

POST http://localhost:8080/api/send_message HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "text" : "test",
    "number": "089636811489"
}